defaults:
  - defaults

_target_: src.strategies.OLDAnchorALWithEntropy
num_neighbours: 50
max_search_size: null
anchor_strategy_minority: kmeans_pp_sampling
anchor_strategy_majority: kmeans_pp_sampling
num_anchors: 50
aggregate_by_class_first: false