defaults:
  - defaults

_target_: src.strategies.AnchorAL

num_neighbours: 2000
max_search_size: null

anchor_strategy: random  # all, random, kmeans
only_minority: true
num_anchors: 50

subpool_size: 10000  # if null returns all unique
agg_fn: mean 
temperature: 1.
subpool_sampling_strategy: importance  # uniform, importance, top-k