defaults:
  - _self_
  - callbacks:
    # - pytorch_profiler
    - save_outputs
    - timer
  - loggers:
    - tensorboard
  - optional strategy: null
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${experiment_group}/${dataset_name}_${now:%Y-%m-%d}T${now:%H-%M-%S}
  job_logging:
    formatters:
      colorlog:
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red
  sweep:
    dir: ./outputs/multirun/${experiment_group}/${dataset_name}_${now:%Y-%m-%d}T${now:%H-%M-%S}
    subdir: ${hydra.job.override_dirname}

strategy: null

estimator:
  accelerator: gpu
  strategy: null
  devices: null
  num_nodes: 1
  precision: 32
  plugins: null
  deterministic: true

callbacks: null
loggers: null

model:
  name_or_path: null

data:
  batch_size: 128
  eval_batch_size: 128
  num_workers: 32
  pin_memory: true
  drop_last: false
  persistent_workers: true
  shuffle: true
  seed: ${seed}
  replacement: false
  max_source_length: 512

fit:
  num_epochs: 3
  loss_fn: null
  loss_fn_kwargs: null
  learning_rate: 0.001
  optimizer: adamw
  optimizer_kwargs: null
  scheduler: constant_schedule
  scheduler_kwargs: null
  log_interval: ${log_interval}
  progress_bar: ${progress_bar}
  limit_train_batches: ${limit_batches}
  limit_validation_batches: ${limit_batches}

validation:
  log_interval: ${log_interval}
  progress_bar: ${progress_bar}
  limit_batches: ${limit_batches}

test:
  log_interval: ${log_interval}
  progress_bar: ${progress_bar}
  limit_batches: ${limit_batches}

active_fit:
  num_rounds: 20
  query_size: 50
  val_perc: 0.3
  reinit_model: true
  limit_pool_batches: ${limit_batches}

# global settings
log_interval: 1
progress_bar: true
limit_batches: null

dataset_name: '???'
seed: 42
experiment_group: dry_run