defaults:
  - _self_
  - loggers:
    - tensorboard
  - optional strategy: null
  - optional dataset: null
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

hydra:
  job:
    chdir: true
  run:
    dir: ./outputs/${experiment_group}/${dataset.short_name}/${get_name_strategy:${strategy}}_${now:%Y-%m-%d}T${now:%H-%M-%S}
  job_logging:
    formatters:
      colorlog:
        format: '[%(cyan)s%(asctime)s%(reset)s][%(blue)s%(name)s%(reset)s][%(log_color)s%(levelname)s%(reset)s] - %(message)s'
        log_colors:
          DEBUG: purple
          INFO: green
          WARNING: yellow
          ERROR: red
          CRITICAL: bold_red
  sweep:
    dir: ./outputs/multirun/${experiment_group}/${dataset.short_name}/
    subdir: ${get_name_strategy:strategy}_${now:%Y-%m-%d}T${now:%H-%M-%S}

estimator:
  accelerator: gpu
  precision: 32
  deterministic: true

callbacks: null
loggers: null

data:
  batch_size: 32
  eval_batch_size: 256
  num_workers: 32
  pin_memory: true
  drop_last: false
  persistent_workers: true
  shuffle: true
  seed: ${seed}
  replacement: false
  max_length: 512

# this is incremental to `data` above
active_data:
  budget: null
  validation_perc: ${active_fit.validation_perc}
  sampling: ${active_fit.validation_sampling}
  seed: ${seed}
  positive_budget: null

fit:
  max_epochs: 3
  min_steps: null
  learning_rate: 0.0002
  optimizer: adamw
  optimizer_kwargs: null
  scheduler: null
  scheduler_kwargs: null
  log_interval: ${log_interval}
  enable_progress_bar: ${enable_progress_bar}
  num_validation_per_epoch: 1
  limit_train_batches: ${limit_batches}
  limit_validation_batches: ${limit_batches}

# this is incremental to `fit` above
active_fit:
  max_rounds: 50
  max_budget: null
  query_size: 25
  validation_perc: 0.3
  validation_sampling: stratified
  reinit_model: true
  limit_pool_batches: ${limit_batches}
  limit_test_batches: ${limit_batches}

test:
  log_interval: ${log_interval}
  enable_progress_bar: ${enable_progress_bar}
  limit_batches: ${limit_batches}

strategy: '???'
model: '???'
embedding_model: null
dataset: '???'

# global settings
log_interval: 1
enable_progress_bar: true
limit_batches: null
seed: 42
experiment_group: dry_run
