early_stopping:
  _target_: energizer.callbacks.early_stopping.EarlyStopping
  monitor: train/f1_class1
  stage: train
  interval: epoch
  mode: max
  min_delta: 0.00001
  patience: 10
  stopping_threshold: null
  divergence_threshold: null
  verbose: true
