early_stopping:
  _target_: src.energizer.callbacks.EarlyStopping
  monitor: f1_macro
  stage: validation
  interval: epoch
  mode: max
  min_delta: 0.00001
  patience: 20
  stopping_threshold: null
  divergence_threshold: null
  verbose: false

