model_checkpoint:
  _target_: energizer.callbacks.model_checkpoint.ModelCheckpoint
  dirpath: .checkpoints
  monitor: train/f1_class1
  stage: train
  mode: max
  save_last: false
  save_top_k: 1
  verbose: true


