model_checkpoint:
  _target_: energizer.callbacks.model_checkpoint.ModelCheckpoint
  dirpath: .checkpoints
  monitor: f1_macro
  stage: train
  mode: max
  save_last: true
  save_top_k: 1
  verbose: true
