pytorch_profiler:
  _target_: energizer.callbacks.pytorch_profiler.PytorchTensorboardProfiler
  dirpath: tb_logs
  wait: 1
  warmup: 1
  active: 1
  repeat: 2
  record_shapes: true
  with_stack: true
  with_flops: true
  profile_memory: true